- docs/브랜치 전략.md
- 이해가 되지 않는 부분 or 수정이 필요한 부분에 Comment 달아주세요.
- 모든 팀원에게 Approve 받은 시점 merge 하겠습니다.
> docs: 브랜치 전략 추가

- BE/eeos/src/main/java/com/blackcompany/eeos/program/persistence/ProgramEntity.java
closed #52 
program_date column 에러를 해결합니다.
> [BE/FIX] column 에러 해결

- BE/eeos/docker-compose.yml
- BE/eeos/src/main/resources/application-local-mysql.yml
closed #85 
멍청했습니다...
docker로 mysql를 열 때 기본적으로 timezone 세팅을 UTC로 해두고 있었습니다...
전 기존에 docker로 연 mysql 내부에서 UTC 설정을 Asia/Seoul 설정으로 바꿨고(변경 내역도 있습니다!)
근데, 왜 후작업이 안 먹힌 걸까요?
이건 아직 의문입니다....
중간에 글 며칠 사라지는 것도 위에 대한 의문을 해결하면 알아낼 수 있을 듯 합니다..!
(내일 회의 시간 전까지 정리해서 가겠습니다~!)
> [BE/BUG] 타임존 문제 해결

- BE/eeos/docker-compose.yml
- BE/eeos/src/main/resources/application-local-mysql.yml
> [BE] Term2 - Sprint2

- BE/eeos/docker-compose.yml
- BE/eeos/src/main/java/com/blackcompany/eeos/config/WebMvcConfig.java
- BE/eeos/src/main/resources/application-dev-api.yml
- BE/eeos/src/main/resources/application-local-api.yml
- BE/eeos/src/main/resources/application-prod-api.yml
- BE/eeos/src/main/resources/application.yml
closed #86 
* 환경별 cors 설정
* docker-compose 외부에서 주입하도록 하여 환경별 구축
> [BE/BUG] term1 환경별 cors 설정

- FE/src/app/(auth)/login/name-error/page.tsx
> hotfix: NAME_MANUAL_URL 수정 및 .env 파일에서 관리

- FE/src/app/(auth)/login/name-error/page.tsx
- FE/src/components/programCreate/ProgramCreateForm.tsx
> hotfix: NAME MANUAL URL 수정 및 .env에서 관리

- FE/package.json
- FE/pnpm-lock.yaml
- FE/src/app/(auth)/layout.tsx
- FE/src/app/(auth)/login/page.tsx
- FE/src/app/(private)/(program)/detail/[programId]/page.tsx
- FE/src/app/(private)/(program)/layout.tsx
- FE/src/app/globals.css
- FE/src/app/layout.tsx
- FE/src/components/common/Title.tsx
- FE/src/components/common/form/ProgramForm.tsx
- FE/src/components/common/header/CreateBtn.tsx
- FE/src/components/common/header/Header.tsx
- FE/src/components/common/header/Modal/UserActiveModal.tsx
- FE/src/components/common/header/UserBtn.tsx
- FE/src/components/common/markdown/MarkdownEditor.tsx
- FE/src/components/common/markdown/MarkdownViewer.tsx
- FE/src/components/common/memberTable/MemberTable.tsx
- FE/src/components/common/memberTable/MemberTableHeader.tsx
- FE/src/components/common/pagination/Pagination.tsx
- FE/src/components/common/pagination/PaginationItem.tsx
- FE/src/components/common/tabs/Tab.tsx
- FE/src/components/login/LeftSection.tsx
- FE/src/components/login/RightSection.tsx
- FE/src/components/main/ProgramListItem.tsx
- FE/src/components/programCreate/CreateMemberTableItem.tsx
- FE/src/components/programDetail/program/EditAndDeleteButton.tsx
- FE/src/components/programDetail/program/ProgramHeader.tsx
- FE/src/components/programDetail/userAttendModal/UserAttendModal.container.tsx
- FE/src/components/programEdit/EditMemberTableItem.tsx
- FE/tailwind.config.ts
related #209 
closed #209 
반응형이 적용되지 않은 부분 구현
> [FE/FEAT] 반응형 적용

- AI/model.py
> docs: 엔드포인트 및 변수 명 변경

- AI/model.py
#245 
최소인원 지정을 삭제하고 최대 인원만 지정할 수 있도록 최소 인원을 합치는 부분의 코드를 삭제.
> [AI/FEAT] 최소 인원 지정 삭제

- AI/main.py
> feat: 443 포트 적용을 위한 api 생성

- AI/main.py
- AI/model.py
> [AI/FEAT] health check 를 위한 API 생성

- AI/model.py
> [AI/DOCS] 변수명 수정

- AI/main.py
- AI/model.py
> [FIX/AI] request json 변경으로 인한 수정

- AI/model.py
#252
Item안의 name을 memberId로 변경한다.
클러스터링 결과를 memberId로 출력할 수 있도록 한다.
> [AI/FEAT] 클러스터링 결과를 memberId로 출력

- FE/src/apis/teamBuilding.ts
- FE/src/components/teamBuildingDetail/teamBuilding/TeamBuildingHeader.tsx
- FE/src/constants/API.ts
- FE/src/hooks/query/useTeamBuildingQuery.ts
> [FE/FEAT] 팀빌딩 삭제 기능 구현

- BE/eeos/src/main/java/com/blackcompany/eeos/target/application/service/QueryTeamBuildingTargetService.java
> [BE/FIX] 별도의 트랜젝션으로 실행하도록 트랜젝션 분리

- AOS/AOS-README.md
> [DOCS/AOS] 안드로이드 리드미 파일 작성

- BE/README.md
* tech stack
* 관련 문서
* 실행하는 방법
> [BE/DOCS] README를 적용한다.

- AI/AI_README.md
> [AI/Docs] ai readme 

- AI/AI_README.md
- AI/model.py
eeos 내부의 ai를 사용하기 위한 readme 작성
> [AI/DOCS] AI readme

- BE/README.md
closed #286 
* Cache Control, ETag를 적용하였습니다.
> [BE/FEAT]캐시를 적용한다.

- BE/README.md
- README.md
closed #301 
* 아키텍처 추가하였습니다.
* 노션 링크 -> 각 파일에 맞는 링크로 변경하였습니다.
아키텍처 변경하고 싶으신 부분이나, 글 바꾸시고 싶으신 부분 있으시면 review 남겨주세요!! @JNU-econovation/eeos
> [ALL/DOCS] README 작성
